name: ontimenow
description: A multi-functional clock application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  audioplayers: ^5.2.1
  intl: ^0.19.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpah_ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
